Update to qpid-cpp 0.28

diff --git a/src/tests/run_paged_queue_tests b/src/tests/run_paged_queue_tests
--- a/src/tests/run_paged_queue_tests
+++ b/src/tests/run_paged_queue_tests
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 #
 # Licensed to the Apache Software Foundation (ASF) under one
@@ -26,7 +26,7 @@ trap stop_broker INT TERM QUIT
 export PATH=$PWD:$srcdir:$PYTHON_COMMANDS:$PATH
 
 start_broker() {
-    QPID_PORT=$($QPIDD_EXEC --daemon --port 0 --interface 127.0.0.1 --no-data-dir $MODULES --auth no) || fail "Could not start broker"
+    QPID_PORT=$($QPIDD_EXEC --daemon --port 0 --interface 127.0.0.1 --no-data-dir --paging-dir=$PWD/pqtest_data $MODULES --auth no) || fail "Could not start broker"
 }
 
 stop_broker() {
