update to upstream qpid 0.34

diff --git a/etc/qpidd-primary.in b/etc/qpidd-primary.in
--- a/etc/qpidd-primary.in
+++ b/etc/qpidd-primary.in
@@ -37,27 +37,27 @@
 
 prog=qpidd
 
-# Source function library.
-. /etc/rc.d/init.d/functions
-
-if [ -f @sysconfdir@/sysconfig/$prog ] ; then
-    . @sysconfdir@/sysconfig/$prog
-fi
-
 # The following variables can be overridden in @sysconfdir@/sysconfig/$prog
-[[ $QPID_PORT ]] || QPID_PORT=5672
-[[ $QPID_HA ]]   || QPID_HA=@bindir@/qpid-ha
-export QPID_PORT
+QPID_INIT=@initdir@/$prog
+QPID_CONFIG=@confdir@/qpidd.conf
+QPID_HA=@bindir@/qpid-ha
+QPID_HA_OPTIONS="--config $QPID_CONFIG"
+
+# Source configuration
+test -f @sysconfdir@/sysconfig/$prog && source @sysconfdir@/sysconfig/$prog
+source /etc/rc.d/init.d/functions
+
+# Check presence of executables/scripts
+for f in $QPID_INIT $QPID_HA; do
+    test -x $f || { echo "$f not found or not executable"; exit 5; }
+done
+
+QPID_HA="$QPID_HA $QPID_HA_OPTIONS"
 
 RETVAL=0
 
-#ensure binary is present and executable
-if [[ !(-x $QPID_HA) ]]; then
-    echo "qpid-ha executable not found or not executable"
-fi
-
 status() {
-    if $QPID_HA -b localhost:$QPID_PORT status --is-primary ; then
+    if $QPID_HA status --is-primary ; then
 	echo "qpidd is primary"
     else
 	echo "qpidd is not primary"
@@ -65,24 +65,35 @@ status() {
     fi
 }
 
+# Ensure no concurrent start/stop of services.
+lock() {
+    export QPID_HA_LOCK_HELD=1	# For calls to the qpidd script
+    exec 9< $QPID_INIT
+    flock 9
+}
+
 start() {
-    service qpidd start
-    echo -n $"Promoting qpid daemon to cluster primary: "
-    $QPID_HA -b localhost:$QPID_PORT promote
-    [ "$?" -eq 0 ] && success || failure
+    lock
+    $QPID_INIT start primary || return $?
+    echo -n $"Promoting to primary: "
+    err=$($QPID_HA promote --cluster-manager 2>&1)
+    RETVAL=$?
+    [ $RETVAL = 0 ] && success || { echo -n "$err: "; failure; }
+    echo
+    return $RETVAL
 }
 
 stop() {
-    service qpidd stop
+    $QPID_INIT stop primary
 }
 
 reload() {
     echo 1>&2 $"$0: reload not supported"
-    exit 3
+    return 3
 }
 
 restart() {
-    service qpidd restart && start
+    stop && start
 }
 
 # See how we were called.
diff --git a/etc/qpidd.in b/etc/qpidd.in
--- a/etc/qpidd.in
+++ b/etc/qpidd.in
@@ -39,79 +39,128 @@ prog=qpidd
 lockfile=/var/lock/subsys/$prog
 pidfile=/var/run/qpidd.pid
 
+# The following variables can be overridden in @sysconfdir@/sysconfig/$prog
+QPID_INIT=@initdir@/$prog
+QPID_BIN=@sbindir@/$prog
+QPID_DATA_DIR=/var/lib/qpidd
+QPID_CONFIG=@confdir@/qpidd.conf
+QPID_HA=@bindir@/qpid-ha
+QPID_HA_OPTIONS="--config $QPID_CONFIG"
+
 # Source configuration
-if [ -f @sysconfdir@/sysconfig/$prog ] ; then
-	. @sysconfdir@/sysconfig/$prog
+test -f @sysconfdir@/sysconfig/$prog && source @sysconfdir@/sysconfig/$prog
+source /etc/rc.d/init.d/functions
+
+# Data dir: respect the config file if set.
+grep -q '^ *data-dir *=' $QPID_CONFIG || QPIDD_OPTIONS="$QPIDD_OPTIONS --data-dir=$QPID_DATA_DIR"
+
+# Check for HA configuration
+if grep -iq '^ *ha-cluster *= *\(true\|on\|1\|yes\)' $QPID_CONFIG; then
+    # HA is configured, do some extra checks.
+    test -x  $QPID_HA || { echo "HA configured but $QPID_HA not found"; return 5; }
+
+    ha_ping() {	$QPID_HA $QPID_HA_OPTIONS ping >/dev/null 2>&1; }
+
+    ha_allow_stop() {
+        # Primary script does not stop backup brokers and vice versa.
+	if $QPID_HA $QPID_HA_OPTIONS status --is-primary 2>&1 > /dev/null; then
+	    [ "$1" = primary ] || { echo -n "stop primary broker with 'qpidd-primary stop'"; return 1; }
+	else
+	    [ "$1" = primary ] && { echo -n "stop backup broker with 'qpidd stop'"; return 1; }
+	fi
+	return 0
+    }
+else
+    # No HA configuration, HA checks are no-ops.
+    ha_ping() { true; }
+    ha_allow_stop() { true; }
 fi
 
-# Source function library.
-. /etc/rc.d/init.d/functions
+# Check presence of executables/scripts
+for f in $QPID_BIN; do
+    test -x $f || { echo "$f not found or not executable"; exit 5; }
+done
 
 RETVAL=0
 
-#ensure binary is present and executable
-if [[ !(-x @sbindir@/$prog) ]] ; then
-    echo "@sbindir@/$prog not found or not executable"
-    exit 5
-fi
-
-#ensure user has sufficient permissions
+# Ensure user has sufficient permissions
 runuser -s /bin/sh qpidd -c "echo x > /dev/null" 2> /dev/null || RETVAL=4
 if [ $RETVAL = 4 ]; then
     echo "user had insufficient privilege";
     exit $RETVAL
 fi
 
+do_status() {
+    # Check PID file and ping for liveness
+    MESSAGE=$(status -p $pidfile $prog) && {
+	ha_ping || return 1
+    }
+    RC=$?
+    echo $MESSAGE
+    return $RC
+}
+
+FLOCK_FD=9
+# Ensure no concurrent start/stop of services.
+lock() {
+    [ "$QPID_HA_LOCK_HELD" ] || { # Held by caller
+	exec 9< $QPID_INIT
+	flock $FLOCK_FD
+    }
+}
+
 start() {
-        [[ $QPID_DATA_DIR ]] || QPID_DATA_DIR=/var/lib/qpidd
-        echo -n $"Starting Qpid AMQP daemon: "
-	daemon --pidfile $pidfile --check $prog --user qpidd @sbindir@/$prog --data-dir $QPID_DATA_DIR --daemon $QPIDD_OPTIONS
-	RETVAL=$?
-	echo
-	[ $RETVAL = 0 ] && touch $lockfile
-	if [ $RETVAL = 0 ]; then
-	    touch $pidfile
-	    chown qpidd.qpidd $pidfile
-            [ -x /sbin/restorecon ] && /sbin/restorecon $pidfile
-	    runuser - -s /bin/sh qpidd -c "@sbindir@/$prog --check > $pidfile"
-	fi
-	return $RETVAL
+    lock
+    echo -n $"Starting Qpid AMQP daemon: "
+    touch $pidfile
+    chown qpidd.qpidd $pidfile
+    [ -x /sbin/restorecon ] && /sbin/restorecon $pidfile
+    daemon --pidfile $pidfile --check $prog --user qpidd $QPID_BIN --config $QPID_CONFIG --daemon $QPIDD_OPTIONS --close-fd $FLOCK_FD --pidfile $pidfile
+    RETVAL=$?
+    echo
+    [ $RETVAL = 0 ] && touch $lockfile
+    return $RETVAL
 }
 
 stop() {
+    lock
+    if ha_allow_stop $1; then
 	echo -n $"Stopping Qpid AMQP daemon: "
 	killproc -p ${pidfile} $prog
 	RETVAL=$?
-	echo
 	[ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
+    fi
+    [ "$RETVAL" = 0 ] && success
+    echo
+    return $RETVAL
 }
 
+
 reload() {
-	echo 1>&2 $"$0: reload not supported"
-	exit 3
+    echo 1>&2 $"$0: reload not supported"
+    return 3
 }
 
 restart() {
-	stop
-	start
+    stop && start
 }
 
 # See how we were called.
 case "$1" in
-  start|stop|restart|reload)
-	$1
+    start|stop|restart|reload)
+	$1 $2
 	;;
-  status)
-	status $prog
+    status)
+	do_status
 	RETVAL=$?
 	;;
-  force-reload)
+    force-reload)
 	restart
 	;;
-  try-restart|condrestart)
+    try-restart|condrestart)
 	[ -e $lockfile ] && restart || :
 	;;
-  *)
+    *)
 	echo 1>&2 $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|force-reload}"
 	exit 2
 esac
